# Generated by Django 4.1.7 on 2023-02-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_room_code'),
        ('api', '0002_auto_20201218_1626'),
    ]

    operations = [
    ]
