# Generated by Django 4.1.7 on 2023-03-01 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_alter_room_code_0002_auto_20201218_1626'),
        ('api', '0003_room_current_song'),
    ]

    operations = [
    ]
